### ISSUE TITLE
buffer too small

### ISSUE THREAD

**Issue by wx4cb** [roger357/HeimDallMultiwii#1]
I am using your simple test program as a base.

when trying to get the raw gps information, i get a buffer overrun error:

```
charlesb@GroundStation:~/src/msp/HeimDallMultiwii$ python3 test.py
Connecting with board on port: /dev/ttyACM0
Connection Stablished.
{'VERSION': 231, 'MULTITYPE': 3, 'MSP_VERSION': 0, 'capability': 2147483708}
{'cycleTime': 2008, 'i2c_errors_count': 45, 'sensor': 195, 'flag': 65536, 'global_conf.currentSet': 0}
{'accx': -127, 'accy': -357, 'accz': 381, 'gyrx': 0, 'gyry': -3, 'gyrz': 3, 'magx': 0, 'magy': 0, 'magz': 0}
{'servo1': 1500, 'servo2': 1500, 'servo3': 1500, 'servo4': 1500, 'servo5': 1500, 'servo6': 1500, 'servo7': 1500, 'servo8': 1500}
{'accx': -128, 'accy': -356, 'accz': 382, 'gyrx': 1, 'gyry': 1, 'gyrz': 2, 'magx': 0, 'magy': 0, 'magz': 0}
Traceback (most recent call last):
  File "test.py", line 17, in <module>
    print(droneFCB.get_rawgps())
  File "/home/charlesb/src/msp/HeimDallMultiwii/HeimdallMultiwii/comm.py", line 55, in get_rawgps
    return self._send_message(MSPMessagesEnum.MSP_RAW_GPS.value)
  File "/home/charlesb/src/msp/HeimDallMultiwii/HeimdallMultiwii/comm.py", line 140, in _send_message
    msg = self.flightcontrolboard.get_fcb_data(cmd)
  File "/home/charlesb/src/msp/HeimDallMultiwii/HeimdallMultiwii/multiwii.py", line 101, in get_fcb_data
    return self._readmessage(code)
  File "/home/charlesb/src/msp/HeimDallMultiwii/HeimdallMultiwii/multiwii.py", line 114, in _readmessage
    msg = struct.unpack('<' + fmt, data)
struct.error: unpack requires a buffer of 16 bytes
```

```
charlesb@GroundStation:~/src/msp/HeimDallMultiwii$ cat test.py
#!/usr/bin/env python3
from HeimdallMultiwii import comm
import time

droneFCB = comm.Adapter('/dev/ttyACM0') #  default baudrate 115200
# OR your custom baudrate                           vvvvv
# droneFCB = comm.Adapter('/dev/ttyUSB0', baud_rate=56000)
droneFCB.connect()
if droneFCB.can_fly():
    print(droneFCB.get_ident())
    print(droneFCB.get_status())
    print(droneFCB.get_rawimu())
    print(droneFCB.get_servo())

while True:
    print(droneFCB.get_rawimu())
    print(droneFCB.get_rawgps())
    time.sleep(0.25)
```

**Comment by rgr-dev** [comment]
Hello @wx4cb Thanks for take the time for test this repo, 
Today code in [this](https://github.com/roger357/HeimDallMultiwii/commits/feature/HEIMDALL_201904) branch returns rawgps without problems. 

I have been forced to make specific and customized changes to both the code in this repository and the Firmware of the FCB that I am using.

I must take the time to update the README file of the project to clarify these changes that I have been forced to do.

This issue will be opened until the changes that i mentioned will committed. Later, if you can test again and we can close it if all works fine.

Regards.

**Comment by rgr-dev** [comment]
Dear @wx4cb, The repo was updated :)
Please test and let me know if everything its OK.
